var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/workspace/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__109qvc_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0xuwr5d.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yvo~da._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00mujn-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gdna-1._.js")
R.c("server/chunks/ssr/web_app_error_tsx_007_a_r._.js")
R.c("server/chunks/ssr/web_app_not-found_tsx_0hj1lzp._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/web_app_global-error_tsx_0uvsy8l._.js")
R.c("server/chunks/ssr/web__next-internal_server_app_workspace_page_actions_0g9.my5.js")
R.m(61336)
module.exports=R.m(61336).exports
