var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lz7s_y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0nrpfj3.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yvo~da._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00mujn-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gdna-1._.js")
R.c("server/chunks/ssr/web_app_error_tsx_007_a_r._.js")
R.c("server/chunks/ssr/web_app_not-found_tsx_0hj1lzp._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/web_app_global-error_tsx_0uvsy8l._.js")
R.c("server/chunks/ssr/web__next-internal_server_app_page_actions_10mwvn..js")
R.m(98641)
module.exports=R.m(98641).exports
