var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/infrastructure/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j38axi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_13vf9__.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yvo~da._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00mujn-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gdna-1._.js")
R.c("server/chunks/ssr/web_app_error_tsx_007_a_r._.js")
R.c("server/chunks/ssr/web_app_not-found_tsx_0hj1lzp._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/web_app_global-error_tsx_0uvsy8l._.js")
R.c("server/chunks/ssr/web__next-internal_server_app_infrastructure_page_actions_03t6~sc.js")
R.m(44647)
module.exports=R.m(44647).exports
